name = "bookeasy-router"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
VERCEL_ORIGIN = "https://bookeasy-landing.vercel.app"
BACKEND_ORIGIN = "https://api.bookeasy.com.ua"

[[routes]]
pattern = "bookeasy.com.ua/*"
zone_name = "bookeasy.com.ua"
